name: Build Docker Image Only

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image
        run: |
          docker build -t myquiz-backend:latest ./Backend/QuizAPI

      - name: Save Docker image as tarball artifact
        run: |
          docker save myquiz-backend:latest -o backend-image.tar
